# Generated by Django 5.1.5 on 2025-03-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdetails',
            name='quiz_duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes, you badass'),
        ),
    ]
